project:
  type: website
  output-dir: docs
  
website:
  title: "STA9750 2024 Submission Materials"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://Timbila614.github.io/STA9750-2024-FALL/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: united
    toc: false
  